### ISSUE TITLE
Setup YAPF (or other formatter)

### ISSUE THREAD

**Issue by Wmyers559** [DragonAxe/CSE423-Compiler-Collective#3]
From a _very_ brief search, it looks like the options for automatic code formatters for Python are YAPF (https://github.com/google/yapf) and Black (https://github.com/psf/black). We should decide which one to use, and set it up.

**Comment by DragonAxe** [comment]
Looks like the biggest difference is that Black has no options (you get what you get) and Yapf allows you to set the base style, then customize it further as you like.
If we wanted to just get a formatter up and running and never change anything, I would go with Black.
If we wanted to allow for possible tweaking of our style, then I would go with Yapf.
Yapf is also a more mature project.
I think I'm kind of leaning towards Yapf.
If it doesn't work for us then we can always switch to Black later on.

**Comment by Wmyers559** [comment]
That is my leaning at the moment. I agree with your assessment on the ease of setup, though from setting up `clang-format` in the past, the setup will not take too long, iirc.

@TheFriendbesto / @niko-rose, any significant feelings on the matter?

**Comment by TheFriendbesto** [comment]
I am leaning towards YAPF as well. I think the flexibility will be worth the time investment, especially as our project grows in size and complexity.

**Comment by Wmyers559** [comment]
Given this, let us use YAPF. I'll put in a bit of effort in the next few days, probably on Thursday, to get it set up. Does anyone have particular preferences on the coding style we use? The four defaults are:
 * PEP8
 * Google
     * Chromium
 * Facebook
[This site](https://yapf.now.sh/) allows you to see what the different styles look like, and [this file](https://github.com/google/yapf/blob/master/yapf/yapflib/style.py#L358) describes the various configurations for all of them in gory detail.

**Comment by Wmyers559** [comment]
Pending any objections, I'm leaning towards a modified version of Google's style guide.

**Comment by DragonAxe** [comment]
Google's style works for me.

**Comment by Wmyers559** [comment]
This has been fixed in #15
